- name: make a directory
  ansible.builtin.file:
    path: /opt
    state: directory

- name: Download sonar-scanner
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux-x64.zip?_gl=1*w374vd*_gcl_au*MTQ0NzA4ODc2MS4xNzQ4MzMyNDU3*_ga*MTAyOTA5MTgwLjE3MTc1OTUzMzA.*_ga_9JZ0GZ5TC6*czE3NDgzMzI0NTYkbzgkZzEkdDE3NDgzMzM3MzckajUzJGwwJGgwJGQzc1Z5UjRsN2tuNjEtNkRVdlEyYS1ZR0xVQ000aW9VUEZR
    dest: /opt
    remote_src: yes

- name: make a directory runner
  ansible.builtin.file:
    path: /home/ec2-user/github-runner
    state: directory
  become_user: ec2-user

- name: Download Github runner
  ansible.builtin.unarchive:
    src:  https://github.com/actions/runner/releases/download/v2.324.0/actions-runner-linux-x64-2.324.0.tar.gz
    dest: /home/ec2-user/github-runner
    remote_src: yes
  become_user: ec2-user

- name: create a runner
  ansible.builtin.shell: ./config.sh --url https://github.com/pdevops78/expense-backend --token A5LROCZCQ6YTPBYUCUWCEYLIHACYQ
  args:
    chdir: /home/ec2-user/github-runner
  become_user: ec2-user

- name: install dependencies
  ansible.builtin.shell: ./bin/installdependencies.sh

- name: runner
  ansible.builtin.shell: ./svc.sh install
  args:
    chdir: /home/ec2-user/github-runner
    become_user: ec2-user






