- name: make a directory runner
  ansible.builtin.file:
    path: /home/ec2-user/github-runner
    state: directory
  become_user: ec2-user

- name: start service runner
  ansible.builtin.shell: ./svc.sh uninstall ;
  args:
    chdir: /home/ec2-user/github-runner

- name: Download Github runner
  ansible.builtin.unarchive:
    src:  https://github.com/actions/runner/releases/download/v2.324.0/actions-runner-linux-x64-2.324.0.tar.gz
    dest: /home/ec2-user/github-runner
    remote_src: yes
  become_user: ec2-user

- name: install dependencies
  ansible.builtin.shell: /home/ec2-user/github-runner/bin/installdependencies.sh
  
- name: create a runner
  ansible.builtin.shell:  ./config.sh remove --token  A5LROCZXR7FA3T4IZPDJEULIHBEKC;./config.sh --unattended --url https://github.com/pdevops78/expense-backend --token  A5LROCZXR7FA3T4IZPDJEULIHBEKC

  args:
    chdir: /home/ec2-user/github-runner
  become_user: ec2-user

# start service github action runner
- name: start service runner
  ansible.builtin.shell: ./svc.sh install ; ./svc.sh start
  args:
    chdir: /home/ec2-user/github-runner







