- name: Download artifactory repo
  ansible.builtin.get_url:
    url: https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo

- name: install artifactory
  ansible.builtin.dnf:
    name: artifactory
    state: installed


Download artifactory:
  https://releases.jfrog.io/artifactory/artifactory-pro-rpms/jfrog-artifactory-pro/jfrog-artifactory-pro-7.104.10.rpm
Install artifactory:
  yum install -y jfrog-artifactory-pro-7.104.10.rpm

  start service:
    service artifactory start

