name: learn-github-actions
on:
  workflow:
jobs:
  called.yml:
    uses: pdevops78/github-reuse-actions/.github/workflows/ci.yml@main
    with:
      project_name: expense-backend
      sonar_login: admin
      sonar_password: admin123
      npm_install: true